name: Multi Environment Workflow

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Select the environment to deploy to"
                required: true
                type: choice
                options:
                    - dev
                    - uat
                    - prod

jobs:

    multi-env-run:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}

        steps:

            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Deploy to Environment
              run: |
                echo "Deploying to ${{ inputs.environment }} environment"
                # Add your deployment commands here based on the selected environment
                if [ "${{ inputs.environment }}" == "dev" ]; then
                    echo "Running deployment script for DEV environment"
                    echo "This is the DEV environment. My variable is ${{ vars.var }}"
                elif [ "${{ inputs.environment }}" == "uat" ]; then
                    echo "Running deployment script for UAT environment"
                    echo "This is the UAT environment. My variable is ${{ vars.var }}"
                elif [ "${{ inputs.environment }}" == "prod" ]; then
                    echo "Running deployment script for PROD environment"
                    echo "This is the PROD environment. My variable is ${{ vars.var }}"
                else
                    echo "Invalid environment selected"
                    exit 1
                fi

            - name: Env Context Information
              run: |
                echo "============================================"
                echo "  SELECTED ENVIRONMENT: ${{ inputs.environment }}"
                echo "============================================"

            - name: If DEV, print DEV specific info
              if: ${{ inputs.environment == 'dev' }}
              run: |
                echo "This is the DEV environment. My variable is ${{ vars.var }}."

            - name: If UAT, print UAT specific info
              if: ${{ inputs.environment == 'uat' }}
              run: |
                echo "This is the UAT environment. My variable is ${{ vars.var }}."

            - name: If PROD, print PROD specific info
              if: ${{ inputs.environment == 'prod' }}
              run: |
                echo "This is the PROD environment. My variable is ${{ vars.var }}."