name: My First Workflow

on: 

    workflow_dispatch: 

    push:

        branches:

            - main

jobs:

    first-run:

        runs-on: ubuntu-latest

        steps:

            - name: Checkout Repository

              uses: actions/checkout@v6

 

            - name: Say Hello

              run: |

                echo "Hello World"

                echo "This is my first workflow"

                pwd

                chmod +x scripts/script.sh

                cd scripts

                ./script.sh

            

            - name: Print GitHub context info

              run: |

                echo "============================================"

                echo "  GITHUB ACTIONS CONTEXT INFORMATION"

                echo "============================================"

                echo "  Who triggered this run: ${{ github.actor }}"

                echo "  What triggered it:      ${{ github.event_name }}"

                echo "  Branch / Ref:           ${{ github.ref }}"

                echo "  Commit SHA:             ${{ github.sha }}"

                echo "  Repository:             ${{ github.repository }}"

                echo "  Run number:             ${{ github.run_number }}"

                echo "  Run ID:                 ${{ github.run_id }}"

                echo "============================================"